# ZSH Home
export ZSH="$HOME/.zsh"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/bipo/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#plugins
# ZSH plugins
source $ZSH/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/plugins/zsh-completions/zsh-completions.plugin.zsh
 
export PATH="/home/bipo/.local/bin:$PATH"

#Config alias 
alias kittyc="nvim $HOME/.config/kitty/kitty.conf"
alias zshc="nvim $HOME/.zshrc && source $HOME/.zshrc"
alias hyprc="nvim $HOME/.config/hypr/hyprland.conf"

#Other alias
alias ewws="$HOME/git/eww/target/release/eww"
alias neo="neofetch --image_size 250 --kitty $HOME/.config/neofetch/img/term.jpg"
alias dot="cd $HOME/git/dotfiles"
alias pdf="zathura"

#Git alias
alias gs="git status"
alias gg="cd $HOME/git"
alias gco="git checkout"
alias gm="git commit -m"
alias gp="git push"

#Functions
func checkgc () {
	echo "$1"| commitlint --verbose
}


eval "$(starship init zsh)"

neo

# bun completions
[ -s "/home/bipo/.bun/_bun" ] && source "/home/bipo/.bun/_bun"

# go
export GOBIN="$(go env GOPATH)/bin"
export PATH="$GOBIN:$PATH"


# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# pnpm
export PNPM_HOME="/home/bipo/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
